---
name: Webhook
author: JaxkDev
version: 1.4.1
api: 3.0.0
main: Jack\DiscordMCPE\Main

commands:
  discord:
    description: Discord commands use /discord help for all cmds
    permission: op
    usage: /discord help
    defualt: true
    aliases:
    - dc
...
